export const AuthErrorCodes = {
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHENTICATED: "AUTH_UNAUTHENTICATED",
  AUTH_INVALID_SCOPE: "AUTH_INVALID_SCOPE",
  AUTH_INVALID_LEVEL: "AUTH_INVALID_LEVEL",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_REGISTRATION_FAILED: "AUTH_REGISTRATION_FAILED",
  AUTH_INVALID_SESSION: "AUTH_INVALID_SESSION",
  AUTH_FAILED: "AUTH_FAILED",
} as const

export type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes]
